// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
  "id": "online.skyroom.skyroom",
  "name": "Skyroom.Online",
  "description": "Skyroom conferencing service plugin for Mattermost.",
  "homepage_url": "https://github.com/skyroomonline/mattermost-plugin-skyroom",
  "support_url": "https://github.com/skyroomonline/mattermost-plugin-skyroom/issues",
  "release_notes_url": "",
  "icon_path": "assets/icon.svg",
  "version": "1.0.0",
  "min_server_version": "5.2.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "SkyroomURL",
        "display_name": "Skyroom Service URL:",
        "type": "text",
        "help_text": "The URL for your Skyroom service, for example https://www.skyroom.online. Defaults to https://www.skyroom.online, which is the public server provided by Skyroom.",
        "placeholder": "https://www.skyroom.online",
        "default": "https://www.skyroom.online"
      },
      {
        "key": "SkyroomAPIKey",
        "display_name": "Your Skyroom API Key:",
        "type": "text",
        "help_text": "In order to call skyroom webservice you need an API Key. Get it and put it here.",
        "placeholder": "",
        "default": ""
      },
      {
        "key": "SkyroomLinkValidTime",
        "display_name": "Skyroom Join Link Valid Duration:",
        "type": "number",
        "help_text": "Enter a number to specify how many minutes the join link for Skyroom service should be valid",
        "placeholder": "",
        "default": 30
      },
      {
        "key": "EncryptionKey",
        "display_name": "Encryption Key:",
        "type": "text",
        "help_text": "Enter 16 character length alphanumeric string to be used as encryption key for AES encryption algorithm",
        "placeholder": "",
        "default": ""
      }
    ]
  }
}
`);

export default manifest;
export const id: string = manifest.id;
export const version: string = manifest.version;
